name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  build: 
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Build the Docker image
          run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
         # Manual approval step
        - name: Manual approval
            if: github.event_name == 'workflow_dispatch'
              run: |
                echo "Manually approve the merge to staging"
          # Add any other instructions or prompts for the approver

      # Wait for manual approval
        - name: Wait for approval
            if: github.event_name == 'workflow_dispatch'
              continue-on-error: true
            run: |
             echo "Waiting for manual approval..."
              sleep 10s
          # Add a loop here to check if the pull request has been approved
          # You can use GitHub API or any other mechanism to check for approval
