name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'Development'
    needs: build-and-publish
    steps:

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'Staging'
    needs: [build-and-publish, deploy-dev]
    steps:

