name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'Developement'
    needs: build-and-publish

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'Production'
    needs: [build-and-publish, deploy-dev]

      

